### ISSUE TITLE
Invalid command: "get"

### ISSUE THREAD

**Issue by amaury1093** [saasify-sh/saasify-frontend-boilerplate-cra#1]
Using saasify 1.20.1, I get

```
$ yarn saasify get
yarn run v1.22.4
$ /Users/amaury/Workspace/reacher/webapp/node_modules/.bin/saasify get
Invalid command: "get"
```

Is the README still up-to-date?

**Comment by transitive-bullshit** [comment]
Hey @amaurymartiny, you need to update your version of saasify to latest.

We're releasing updates pretty frequently, so if you run into something like this, try updating to latest and re-running.

The CLI and API will definitely stabilize over time, we're just not quite there yet.
